makeall:
	mpicc -o homework8_distributed.out homework8_distributed.c timing.c -DDEBUG=1
homework8_distributed:
	mpicc -o homework8_distributed.out homework8_distributed.c timing.c -DDEBUG=1

clean:
	rm -f *.o  *.out

