all:
	gcc matrixMultiplicationOptimized.c timing.c -o matrixMultiplicationOptimized.out -lm
	gcc matrixMultiplicationNaive.c timing.c -o matrixMultiplicationNaive.out -lm

part_1_Optimized:
	
	gcc matrixMultiplicationOptimized.c timing.c -o matrixMultiplicationOptimized.out -lm

part_1_Naive:
	
	gcc matrixMultiplicationNaive.c timing.c -o matrixMultiplicationNaive.out -lm
clean:
	rm ./*.out
